### ISSUE TITLE
symbol id prefix

### ISSUE THREAD

**Issue by dkrnl** [yoriiis/svg-chunk-webpack-plugin#26]
### If the feature solves a problem you have, specify it here.

```svg
<symbol id="icon-filename">
```

### Describe the proposed feature.

```js
    new SvgChunkWebpackPlugin({
      prefix: 'icon-',
    })
````    

### Importance

Nice to have

**Comment by yoriiis** [comment]
Hi @dkrnl, the development seems rather complex to me, as the plugin must work with two other packages (`svgo` and `svgstore`).

May I know why you would need it?

**Comment by dkrnl** [comment]
Hi @yoriiis 

I dont know why :-), just try migrate from [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader?tab=readme-ov-file#symbol-id):
```js
{
  symbolId: filePath => 'icon-' + path.basename(filePath),
}
```

**Comment by yoriiis** [comment]
Delighted to hear it!

I think you can remove the prefix and update the HTML that calls SVG.

```twig
<svg class="icon icon-{{ filename }}">
    <use xlink:href="#{{ filename }}"></use>
</svg>
```

I recommend that you place all your SVG files in the same directory, as this avoids duplication and is not required by the plugin.

**Comment by symc-gail** [comment]
For other people who need this for silly reasons (mine is because i'm trying to build my code with both a legacy version of grunt-svgstore, and this plugin at the same time, and because the old svgstore uses the prefix for completely necessary reasons (there are ids with the same names as the base icon files)), here's a way you can accomplish this:
```js
new SvgChunkWebpackPlugin({
        svgstoreConfig: {
          symbolAttrs: {
            id(oldId) {
              if(oldId.startsWith("icon-")) {
                return oldId;
              }
              return `icon-${oldId}`;
            }
          }
        }
      })
```
