### ISSUE TITLE
Upgrade SVGO package to v2.x.x

### ISSUE THREAD

**Issue by emiliegervais** [yoriiis/svg-chunk-webpack-plugin#4]
### Describe the bug

npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

### Steps to reproduce

To reproduce the problem, simply install the package. 

### Expected behavior

No deprecation warning =)

### SvgChunkWebpackPlugin

2.0.1

### webpack

5.54.0

### Node.js & npm

node: 16.14.2 & npm: 8.5.0

### OS

macOS 12.1

**Comment by emiliegervais** [comment]
@yoriiis The label `bug` was added automatically, there was no other choices and I can't seem to modify it. It ain't really a `bug` though, at least not yet. =)

**Comment by yoriiis** [comment]
Hi @emiliegervais, thanks for the report (the label is automatically added by the issue template configuration).

This has been fixed and merged in `master`. Release [`3.0.0`](https://github.com/yoriiis/svg-chunk-webpack-plugin/releases/tag/3.0.0) is available ! 🎉
The release contains breaking changes, please check the changelogs for details.
